import {useEffect,useState} from 'react';
import {api} from '../services/applicationClient';
import {Card,Badge,Button} from './UI';
export default function AdventureLanding({user,onLogin,onPlay,onExplore,onRead}:{user:any;onLogin:()=>void;onPlay:()=>void;onExplore:()=>void;onRead:(sourceId:string)=>void}){
 const [registry,setRegistry]=useState<any>(null),[player,setPlayer]=useState<any>(null),[path,setPath]=useState('planets'),[answer,setAnswer]=useState<string|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;api('canon/registry').then(r=>{if(live)setRegistry(r)}).catch(()=>{if(live)setError('The live source preview is unavailable. You can still open your expedition board.');});return()=>{live=false}},[]);
 useEffect(()=>{let live=true;setPlayer(null);const load=()=>{if(user)api('player').then(r=>{if(live)setPlayer(r.player)}).catch(()=>{});};load();window.addEventListener('player-updated',load);return()=>{live=false;window.removeEventListener('player-updated',load)}},[user?.uid]);
 const entry=registry?.entities.find((e:any)=>e.scope!=='proposal'&&e.state==='source-mention'&&e.type===path&&e.evidencePreview&&e.sourceIds.length>=2);
 const evidence=entry?.evidencePreview,source=registry?.sources.find((s:any)=>s.id===evidence?.sourceId);
 const choices=source?[source,...registry.sources.filter((s:any)=>s.scope!=='proposal'&&s.id!==source.id).slice(0,2)].sort((a:any,b:any)=>a.title.localeCompare(b.title)):[];
 const active=player?.expeditions?.find((m:any)=>m.state==='active');
 return <section aria-labelledby="adventure-title" className="border border-gold-default/40 bg-gradient-to-br from-gold-default/10 via-neutral-black to-blue-default/10 p-5 sm:p-8 space-y-6">
 <div className="flex flex-wrap gap-6 justify-between items-start"><div className="max-w-2xl"><p className="text-blue-default text-xs uppercase tracking-[.3em]">Play the archive · source expeditions</p><h2 id="adventure-title" className="text-3xl sm:text-4xl uppercase font-bold italic text-gold-default mt-3">Follow a clue. Find your story.</h2><p className="text-neutral-grey text-sm leading-relaxed mt-4">Enter Alien Worlds as your own character. Choose a trail, recover field notes from real stories, and test what the evidence reveals. Every completed investigation adds to your personal journey.</p></div><div className="space-y-3"><Button onClick={user?onPlay:onLogin}>{player?'Open expedition command':user?'Build your character':'Create a character & play'}</Button><Button variant="outline" onClick={onExplore}>Explore the Lore Codex</Button></div></div>
 {active?<Card title={'Continue · '+active.name}><p className="text-sm text-neutral-grey">{active.stage==='route'?'Your first decision: choose which source to investigate.':active.ready?'Both field notes are ready. Compare them and draw your conclusion.':'Your next field note is waiting in its source work.'}</p><div className="flex flex-wrap gap-3 mt-4">{active.objectives.map((o:any)=><Badge key={o.id} color={o.complete?'success':'blue'}>{o.complete?'✓ ':''}{o.title}</Badge>)}</div><div className="flex flex-wrap gap-4 items-center mt-5"><Button onClick={onPlay}>Resume investigation</Button><span className="text-xs text-gold-default">{active.xp} XP on completion</span></div></Card>:<div className="grid lg:grid-cols-[1fr_1.5fr] gap-5"><div><h3 className="text-sm text-gold-default uppercase tracking-widest">Try a field exercise</h3><p className="text-xs text-neutral-grey mt-3 leading-relaxed">No account needed for this preview. Choose a subject, inspect its source, then match the passage. Preview answers do not award XP.</p><div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-1 gap-2 mt-4">{[['planets','Chart a world'],['species','Meet a species'],['factions','Trace an organization']].map(([id,label])=><button key={id} aria-pressed={path===id} onClick={()=>{setPath(id);setAnswer(null)}} className={'text-left border p-3 text-xs uppercase '+(path===id?'border-gold-default text-gold-default bg-gold-default/10':'border-neutral-grey/25 text-neutral-grey')}>{label} →</button>)}</div></div><Card title={entry?'Field note · '+entry.name:'Retrieving a source-backed clue'}>{entry&&<><blockquote className="text-sm text-neutral-grey leading-relaxed border-l border-blue-default/50 pl-4">“{evidence.context}”</blockquote><p className="text-sm text-gold-default mt-4 mb-3">Which source contains this passage?</p><Button variant="outline" onClick={()=>onRead(source.id)}>Inspect the original source</Button><div className="space-y-2 mt-4">{choices.map((s:any)=><button key={s.id} onClick={()=>setAnswer(s.id)} className={'block w-full p-3 text-sm text-left border '+(answer===s.id?'border-gold-default':'border-neutral-grey/20 hover:border-blue-default')}>{s.title}</button>)}</div>{answer&&<p role="status" className="mt-4 text-sm text-blue-default">{answer===source.id?'Field note matched. In a full expedition, you will follow a second appearance and compare what both passages establish.':'That is another work in the archive. Inspect the original source and compare the passage, then try again.'}</p>}</>}{error&&<p role="status" className="text-sm text-neutral-grey">{error}</p>}{registry&&!entry&&<p className="text-sm text-neutral-grey">This category has no eligible two-source trail in the current archive. Choose another subject.</p>}</Card></div>}
 <ol className="grid sm:grid-cols-3 gap-4 border-t border-neutral-grey/20 pt-5 text-xs"><li><span className="text-gold-default">01 · CHOOSE YOUR PATH</span><p className="text-neutral-grey mt-2">Your species, homeworld and interests guide recommendations.</p></li><li><span className="text-gold-default">02 · RECOVER THE EVIDENCE</span><p className="text-neutral-grey mt-2">Read, compare and pin source-backed field notes.</p></li><li><span className="text-gold-default">03 · BUILD YOUR JOURNEY</span><p className="text-neutral-grey mt-2">Complete investigations, earn XP and fill your codex.</p></li></ol>
 </section>;
}
