import {useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Globe2,Users,Landmark,MapPin,Orbit,Search,ArrowUpRight,Network,ChevronLeft,ChevronRight,Compass,Shield,Layers} from 'lucide-react';
import {api} from '../services/applicationClient';
import {Badge,Button} from './UI';
const categories=[{id:'all',label:'All records',icon:Layers},{id:'planets',label:'Planets & worlds',icon:Globe2},{id:'species',label:'Races & species',icon:Users},{id:'factions',label:'Organizations',icon:Landmark},{id:'characters',label:'Characters',icon:Compass},{id:'locations',label:'Places',icon:MapPin},{id:'technology',label:'Technology',icon:Orbit},{id:'events',label:'Events',icon:Compass},{id:'vehicles',label:'Vessels',icon:Orbit},{id:'creatures',label:'Creatures',icon:Compass}];
const normalType=(type:string)=>({character:'characters',location:'locations',vehicle:'vehicles',creature:'creatures'}[type]||type);
const category=(type:string)=>categories.find(c=>c.id===normalType(type))||{id:type,label:type,icon:BookOpen};
const clean=(text:string='')=>text.replace(/<[^>]*>/g,'').replace(/[#*_`]/g,'').replace(/\s+/g,' ').trim();
const worldArt:Record<string,string>={eyeke:'iPS42_Eyeke.png',kavian:'iPS42_Kavian.png',magor:'iPS42_Magor.png',naron:'iPS42_Naron.png',neri:'iPS42_Neri.png',veles:'iPS42_Veles.png'};
export default function CanonExplorer({onRead,user,onLogin}:{onRead:(id:string)=>void;user:any;onLogin:()=>void}){
 const [registry,setRegistry]=useState<any>(null),[search,setSearch]=useState(''),[kind,setKind]=useState('all'),[scope,setScope]=useState('all'),[mode,setMode]=useState('dossiers'),[facet,setFacet]=useState(''),[candidates,setCandidates]=useState(false),[selected,setSelected]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(0),[dossierTab,setDossierTab]=useState('overview'),[sourcePage,setSourcePage]=useState(0);
 const request=useRef(0),top=useRef<HTMLDivElement>(null);
 function reload(){setError('');api('canon/registry').then(setRegistry).catch(e=>setError(e.message));}
 useEffect(reload,[]);
 const sources=registry?.sources||[],entities=registry?.entities||[];
 const sourceMap=useMemo(()=>new Map<string,any>(sources.map((s:any)=>[s.id,s])),[registry]);
 const isProposal=(s:any)=>s?.scope==='proposal'||s?.type==='proposed'||s?.status==='proposal'||s?.provenance?.includes('proposal')||s?.id?.startsWith('lore_worlds_')||s?.id?.startsWith('proposal_');
 const scoped=(s:any)=>scope==='all'||(scope==='archive'?!isProposal(s):isProposal(s));
 const facetEntity=entities.find((e:any)=>e.id===facet);
 const eligibleSources=sources.filter((s:any)=>scoped(s)&&(!facetEntity||facetEntity.sourceIds.includes(s.id)));
 const eligibleIds=new Set(eligibleSources.map((s:any)=>s.id));
 const query=search.trim().toLowerCase();
 const list=entities.filter((e:any)=>(candidates?e.state==='candidate':e.state==='source-mention')&&(kind==='all'||normalType(e.type)===kind)&&e.sourceIds.some((id:string)=>eligibleIds.has(id))&&clean(e.name+' '+e.aliases.join(' ')+' '+(e.summary||'')+' '+(e.classification||'')).toLowerCase().includes(query));
 const storyList=eligibleSources.filter((s:any)=>!query||clean(s.title+' '+(s.summary||'')).toLowerCase().includes(query)||entities.some((e:any)=>e.sourceIds.includes(s.id)&&e.name.toLowerCase().includes(query))).filter((s:any)=>kind==='all'||entities.some((e:any)=>normalType(e.type)===kind&&e.state==='source-mention'&&e.sourceIds.includes(s.id)));
 useEffect(()=>{setPage(0);},[search,kind,scope,facet,candidates,mode]);
 async function open(id:string){const serial=++request.current;setError('');setNotice('');setBusy(true);try{const entity=await api('canon/registry/'+encodeURIComponent(id));if(serial!==request.current)return;setSelected(entity);setNote('');setDossierTab('overview');setSourcePage(0);top.current?.scrollIntoView({behavior:'auto',block:'start'});}catch(e:any){if(serial===request.current)setError(e.message);}finally{if(serial===request.current)setBusy(false);}}
 async function discover(){if(!user){onLogin();return;}try{await api('player/discover',{kind:'entity',target:selected.id});window.dispatchEvent(new Event('player-updated'));setNotice('Discovery recorded in your personal codex.');}catch(e:any){setError(e.message);}}
 async function review(status:string){try{await api('canon/registry/'+encodeURIComponent(selected.id)+'/review',{status,note});await open(selected.id);}catch(e:any){setError(e.message);}}
 function reset(){request.current++;setSelected(null);setBusy(false);setError('');setNotice('');}
 function showStories(id:string){setFacet(id);setMode('stories');setKind('all');setSearch('');reset();}
 const related=selected?entities.filter((e:any)=>e.id!==selected.id&&e.state==='source-mention').map((e:any)=>({...e,shared:e.sourceIds.filter((id:string)=>selected.evidence.some((v:any)=>v.sourceId===id))})).filter((e:any)=>e.shared.length).sort((a:any,b:any)=>b.shared.length-a.shared.length||a.name.localeCompare(b.name)):[];
 const grouped=selected?[...new Set<string>(selected.evidence.map((e:any)=>e.sourceId))].map(id=>({source:sourceMap.get(id),id,evidence:selected.evidence.filter((e:any)=>e.sourceId===id)})):[];
 const tile='border border-neutral-grey/25 bg-neutral-black/70 hover:border-gold-default/70 focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-default transition-colors';
 const entryCard=(e:any)=>{const Icon=category(e.type).icon;const art=worldArt[e.name.toLowerCase()];return <button key={e.id} onClick={()=>open(e.id)} className={tile+' text-left p-5 group relative overflow-hidden min-h-[190px]'}><div className="flex items-start justify-between gap-3">{art?<img src={'/assets/'+art} alt="" className="w-16 h-16 object-contain"/>:<Icon size={30} className="text-blue-default mt-2 mb-6"/>}<span className="text-[10px] text-neutral-grey uppercase tracking-widest">{category(e.type).label}</span></div><h3 className="text-gold-default font-bold text-lg mt-3">{e.name}</h3>{e.summary&&<p className="text-xs text-neutral-white/75 leading-relaxed mt-2 line-clamp-3">…{clean(e.summary)}…</p>}<div className="flex items-center justify-between mt-5 text-xs"><span className="text-neutral-grey">{e.sourceIds.length} source {e.sourceIds.length===1?'work':'works'}</span><ArrowUpRight size={16} className="text-blue-default group-hover:translate-x-1 transition-transform"/></div>{e.scope==='proposal'&&<div className="mt-2"><Badge color="attention">Proposal source</Badge></div>}{e.state==='candidate'&&<Badge color="attention">Needs review</Badge>}</button>};
 return <section ref={top} className="max-w-7xl mx-auto space-y-6 scroll-mt-24">
 <header className="relative border border-gold-default/30 bg-neutral-black/60 p-5 sm:p-8 overflow-hidden"><div className="absolute -right-16 -top-16 w-64 h-64 border border-blue-default/15 rounded-full pointer-events-none"><div className="absolute inset-8 border border-blue-default/15 rounded-full"/><div className="absolute inset-16 border border-gold-default/20 rounded-full"/></div><p className="text-blue-default text-[10px] tracking-[.3em] uppercase relative">Federation knowledge archive</p><h2 className="text-3xl sm:text-4xl font-bold uppercase italic text-gold-default mt-3 relative">Explore the lore</h2><p className="text-sm leading-relaxed text-neutral-white/75 max-w-xl mt-3 relative">Worlds, peoples and powers. Follow their stories, inspect their connections and build your own path through the Alien Worlds universe.</p><div className="flex flex-wrap gap-6 mt-6 text-xs relative">{[[entities.filter((e:any)=>e.state==='source-mention').length,'documented records'],[sources.length,'source works'],[new Set(entities.filter((e:any)=>e.type==='planets'&&e.state==='source-mention').map((e:any)=>e.name)).size,'named worlds']].map(([n,label])=><span key={label as string}><strong className="text-gold-default text-xl mr-2">{registry?n:'—'}</strong><span className="text-neutral-grey">{label}</span></span>)}</div></header>
 {error&&<div role="alert" className="border border-error-default/50 p-4 text-sm">{error}{!registry&&<Button onClick={reload}>Retry loading archive</Button>}</div>}{notice&&<p role="status" className="border border-blue-default/40 p-3 text-sm text-blue-default">{notice}</p>}{busy&&<p role="status" className="text-gold-default">Opening source dossier…</p>}
 {selected?<>
 <div className="flex flex-wrap justify-between gap-3"><Button variant="ghost" onClick={reset}><ChevronLeft size={16}/>Back to archive</Button><Button variant="outline" onClick={()=>showStories(selected.id)}>Browse associated stories</Button></div>
 <div className="grid lg:grid-cols-[260px_1fr] gap-6"><aside className="space-y-5"><div className="border border-blue-default/30 p-5 bg-neutral-black/80">{worldArt[selected.name.toLowerCase()]?<img alt={selected.name} src={'/assets/'+worldArt[selected.name.toLowerCase()]} className="w-36 h-36 object-contain mx-auto mb-4"/>:<Network size={62} className="text-blue-default mx-auto my-6"/>}<p className="text-xs uppercase text-blue-default">{category(selected.type).label}</p><p className="text-xs text-neutral-white/80 mt-2">{selected.classification}</p><h3 className="text-2xl text-gold-default font-bold mt-2 break-words">{selected.name}</h3><div className="mt-4"><Badge color={selected.state==='candidate'?'attention':'blue'}>{selected.state==='candidate'?'Review candidate':'Documented in sources'}</Badge></div><p className="text-xs text-neutral-grey mt-4">{grouped.length} works · {selected.evidence.length} recorded mentions</p>{selected.state==='source-mention'&&selected.scope!=='proposal'&&<Button className="mt-5 text-xs" onClick={discover}>Add to personal codex</Button>}</div><p className="text-xs text-neutral-grey leading-relaxed">A mention identifies a source appearance. Proposed lore and reviewed interpretations remain distinguishable from archive text.</p></aside>
 <div className="min-w-0"><div role="tablist" aria-label="Dossier sections" className="flex overflow-x-auto border-b border-neutral-grey/25 mb-5">{['overview','sources','connections'].map(t=><button role="tab" aria-selected={dossierTab===t} key={t} onClick={()=>setDossierTab(t)} className={'px-4 py-3 text-xs uppercase tracking-widest border-b-2 '+(dossierTab===t?'border-gold-default text-gold-default':'border-transparent text-neutral-grey')}>{t}{t==='sources'?' · '+grouped.length:''}</button>)}</div>
 {dossierTab==='overview'&&<div className="space-y-6"><h4 className="text-gold-default uppercase text-sm">Source briefing</h4>{selected.summary?<p className="text-sm text-neutral-white/85 leading-relaxed">{clean(selected.summary)}</p>:<p className="text-sm text-neutral-grey">Explore the source passages below to establish what is documented about {selected.name}.</p>}{selected.aliases.length>0&&<p className="text-xs text-neutral-grey">Indexed names: {selected.aliases.join(', ')}</p>}<div className="border-l-2 border-blue-default/50 pl-5"><p className="text-[10px] text-blue-default uppercase mb-3">From the source</p><blockquote className="text-sm text-neutral-white/85 leading-7">{clean(selected.evidence[0]?.context)}</blockquote><button onClick={()=>onRead(selected.evidence[0]?.sourceId)} className="text-gold-default text-xs mt-4 hover:underline">Read {sourceMap.get(selected.evidence[0]?.sourceId)?.title||'source work'} →</button></div><h4 className="text-gold-default uppercase text-sm">Explore nearby records</h4><p className="text-xs text-neutral-grey">These records appear in the same works. Shared appearances do not establish a relationship.</p><div className="grid sm:grid-cols-2 gap-3">{related.slice(0,6).map((e:any)=><button key={e.id} onClick={()=>open(e.id)} className={tile+' p-4 text-left'}><span className="text-blue-default text-xs uppercase">{category(e.type).label}</span><strong className="block text-gold-default mt-2">{e.name}</strong><span className="block text-xs text-neutral-grey mt-2">{e.shared.length} shared works →</span></button>)}</div></div>}
 {dossierTab==='sources'&&<div className="space-y-5"><p className="text-sm text-neutral-grey">Every passage links to its full work. Repeated mentions are grouped by source.</p>{grouped.slice(sourcePage*8,(sourcePage+1)*8).map(({source,id,evidence}:any)=><article key={id} className="border border-neutral-grey/25 p-5"><div className="flex flex-wrap gap-2 mb-3"><Badge color={isProposal(source)?'attention':'blue'}>{isProposal(source)?'Proposal narrative':'Pinned archive'}</Badge><span className="text-xs text-neutral-grey">{evidence.length} mentions</span></div><button className="text-gold-default text-lg text-left hover:underline" onClick={()=>onRead(id)}>{source?.title||id}</button><blockquote className="text-sm text-neutral-white/80 leading-7 my-4">{clean(evidence[0].context)}</blockquote><details className="text-xs text-neutral-grey"><summary className="cursor-pointer text-blue-default">Passages & source verification</summary><div className="space-y-3 mt-3">{evidence.slice(1,6).map((e:any)=><p key={e.start}>{clean(e.context)}</p>)}<p>Exact wording: {evidence[0].quote}</p><p className="break-all">SHA-256: {evidence[0].sourceHash}</p>{source?.url&&<a href={source.url} target="_blank" rel="noreferrer" className="inline-block text-blue-default underline">Inspect original source ↗</a>}</div></details></article>)}<div className="flex items-center gap-4"><Button variant="outline" disabled={!sourcePage} onClick={()=>setSourcePage(p=>p-1)}>Previous</Button><span className="text-xs text-neutral-grey">{sourcePage+1} / {Math.max(1,Math.ceil(grouped.length/8))}</span><Button variant="outline" disabled={(sourcePage+1)*8>=grouped.length} onClick={()=>setSourcePage(p=>p+1)}>Next</Button></div></div>}
 {dossierTab==='connections'&&<div className="space-y-5"><h4 className="text-gold-default uppercase text-sm">Connection map</h4><p className="text-sm text-neutral-grey">Choose a record to follow the archive. Solid evidence is shown with its source; co-appearances are exploration links, not inferred canon.</p><div className="border border-blue-default/20 p-5 bg-blue-default/5"><svg viewBox="0 0 640 390" className="w-full hidden sm:block mb-5" role="group" aria-label={'Shared source map for '+selected.name}><circle cx="320" cy="195" r="142" fill="none" stroke="#00baff" strokeOpacity=".15" strokeDasharray="3 7"/>{related.slice(0,8).map((e:any,i:number)=>{const angle=i*Math.PI/4-Math.PI/2,x=320+232*Math.cos(angle),y=195+145*Math.sin(angle);return <g key={e.id}><line x1="320" y1="195" x2={x} y2={y} stroke="#00baff" strokeOpacity=".25"/><g role="button" tabIndex={0} aria-label={'Open '+e.name+' dossier'} onClick={()=>open(e.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open(e.id);}}} className="cursor-pointer"><rect x={x-72} y={y-24} width="144" height="48" rx="3" fill="#101116" stroke="#00baff" strokeOpacity=".5"/><text x={x} y={y-3} fill="#d9a555" textAnchor="middle" fontSize="11">{e.name.length>21?e.name.slice(0,19)+'…':e.name}</text><text x={x} y={y+13} fill="#9a9ea6" textAnchor="middle" fontSize="9">{e.shared.length} shared works</text></g></g>})}<circle cx="320" cy="195" r="66" fill="#15110d" stroke="#d9a555"/><text x="320" y="198" textAnchor="middle" fill="#d9a555" fontSize="12">{selected.name.length>18?selected.name.slice(0,16)+'…':selected.name}</text></svg><div className="text-center text-gold-default font-bold pb-5 border-b border-blue-default/30 sm:hidden">{selected.name}</div><div className="grid sm:grid-cols-2 gap-3 pt-5">{related.slice(0,12).map((e:any)=><button key={e.id} onClick={()=>open(e.id)} className={tile+' text-left p-3'}><span className="text-blue-default text-xs">{category(e.type).label}</span><strong className="block text-neutral-white text-sm mt-1">{e.name}</strong><span className="text-[10px] text-neutral-grey">Co-appears in {e.shared.length} works</span></button>)}</div></div>{selected.relationships?.length>0&&<><h4 className="text-gold-default text-sm">Extracted relationship statements</h4>{selected.relationships.map((r:any,i:number)=><div key={i} className="border-l border-gold-default/30 pl-4 text-sm"><button className="text-blue-default hover:underline" onClick={()=>open(r.targetId)}>{r.predicate.replaceAll('_',' ')} → {entities.find((e:any)=>e.id===r.targetId)?.name||r.targetId}</button><p className="text-xs text-neutral-grey mt-2">{r.status==='candidate'?'Interpretation awaiting review':r.status} · <button onClick={()=>onRead(r.sourceId)} className="underline">Read supporting work</button></p></div>)}</>}{!related.length&&<p className="text-neutral-grey text-sm">No shared source records are indexed yet.</p>}</div>}
 {user?.role==='scribe'&&<details className="mt-8 border-t border-neutral-grey/25 pt-4"><summary className="text-gold-default text-sm cursor-pointer">Scribe evidence review</summary><label className="block text-sm mt-4">Review note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} className="block w-full bg-black p-3 border border-neutral-grey/30 mt-2"/></label><div className="flex flex-wrap gap-2 mt-3">{['accepted','disputed','rejected'].map(s=><Button key={s} disabled={!note.trim()} onClick={()=>review(s)}>{s}</Button>)}</div><p className="text-xs text-neutral-grey mt-3">Records interpretation and preserves review history. Source narratives remain unchanged.</p></details>}
 </div></div></>:<>
 <nav aria-label="Browse lore by category" className="grid grid-cols-2 sm:grid-cols-4 xl:grid-cols-5 gap-2">{categories.map(c=>{const Icon=c.icon;const count=entities.filter((e:any)=>e.state==='source-mention'&&(c.id==='all'||normalType(e.type)===c.id)&&e.sourceIds.some((id:string)=>eligibleIds.has(id))).length;return <button key={c.id} aria-pressed={kind===c.id} onClick={()=>setKind(c.id)} className={'text-left p-3 border transition-colors '+(kind===c.id?'border-gold-default bg-gold-default/10 text-gold-default':'border-neutral-grey/25 bg-neutral-black/60 text-neutral-grey hover:border-blue-default/50')}><Icon size={20} className="mb-3"/><span className="block text-xs">{c.label}</span><span className="block text-lg mt-1">{registry?count:'—'}</span></button>})}</nav>
 <div className="flex flex-wrap items-center gap-3"><div role="tablist" aria-label="Archive display" className="flex border border-neutral-grey/25">{['dossiers','stories'].map(t=><button key={t} role="tab" aria-selected={mode===t} onClick={()=>setMode(t)} className={'px-4 py-3 text-xs uppercase '+(mode===t?'bg-gold-default text-black':'text-neutral-grey')}>{t==='dossiers'?'Entity dossiers':'Story cards'}</button>)}</div><label className="relative flex-1 min-w-[200px]"><Search size={16} className="absolute left-3 top-3 text-neutral-grey"/><span className="sr-only">Search archive records</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a world, people, power or story…" className="w-full bg-black py-3 pl-10 pr-3 border border-neutral-grey/30 text-xs"/></label><select aria-label="Source collection" value={scope} onChange={e=>setScope(e.target.value)} className="bg-black border border-neutral-grey/30 p-3 text-xs"><option value="all">All source collections</option><option value="archive">Pinned main archive</option><option value="proposals">Proposal narratives</option></select></div>
 <div className="flex flex-wrap gap-3 items-center"><label className="text-xs text-neutral-grey flex flex-wrap items-center gap-2">Within stories featuring<select aria-label="Filter by entity" value={facet} onChange={e=>setFacet(e.target.value)} className="bg-black border border-neutral-grey/30 p-2 max-w-full"><option value="">Any world, species or organization</option>{['planets','species','factions'].map(type=><optgroup key={type} label={category(type).label}>{entities.filter((e:any)=>e.type===type&&e.state==='source-mention').map((e:any)=><option key={e.id} value={e.id}>{e.name}</option>)}</optgroup>)}</select></label>{mode==='dossiers'&&<label className="text-xs text-neutral-grey flex gap-2 items-center"><input type="checkbox" checked={candidates} onChange={e=>setCandidates(e.target.checked)}/>Names awaiting review</label>}{(facet||query||kind!=='all'||scope!=='all'||candidates)&&<button className="text-xs text-blue-default underline" onClick={()=>{setFacet('');setSearch('');setKind('all');setScope('all');setCandidates(false);}}>Clear filters</button>}</div>
 {!registry?<p role="status" className="text-neutral-grey">Loading the source archive…</p>:<><div className="flex justify-between items-center"><p role="status" className="text-xs text-neutral-grey">{mode==='dossiers'?list.length:storyList.length} {mode==='dossiers'?'dossiers':'works'}{facetEntity?' featuring '+facetEntity.name:''}</p><span className="text-[10px] text-blue-default uppercase">Evidence linked</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{mode==='dossiers'?list.slice(page*18,(page+1)*18).map(entryCard):storyList.slice(page*18,(page+1)*18).map((s:any)=><article key={s.id} className={tile+' p-5 flex flex-col'}><div className="flex justify-between items-start gap-2"><BookOpen className="text-blue-default" size={24}/><Badge color={isProposal(s)?'attention':'blue'}>{isProposal(s)?'Proposal':'Archive'}</Badge></div><button onClick={()=>onRead(s.id)} className="text-left text-gold-default text-lg font-bold mt-5 hover:underline">{s.title}</button><div className="flex flex-wrap gap-2 my-5">{entities.filter((e:any)=>e.state==='source-mention'&&e.sourceIds.includes(s.id)&&['planets','species','factions'].includes(e.type)).slice(0,5).map((e:any)=><button key={e.id} onClick={()=>open(e.id)} className="text-[10px] text-blue-default border border-blue-default/25 px-2 py-1 hover:bg-blue-default/10">{e.name}</button>)}</div><button className="mt-auto text-left text-xs text-gold-default pt-3 border-t border-neutral-grey/20" onClick={()=>onRead(s.id)}>Read full work →</button></article>)}</div>{!(mode==='dossiers'?list:storyList).length&&<div className="border border-neutral-grey/25 p-8 text-center"><h3 className="text-gold-default">No records match these filters</h3><p className="text-sm text-neutral-grey mt-3">Try another collection or remove a filter to widen your exploration.</p></div>}<div className="flex justify-center items-center gap-4 pt-4"><Button variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={14}/>Previous</Button><span className="text-xs text-neutral-grey">{page+1} / {Math.max(1,Math.ceil((mode==='dossiers'?list:storyList).length/18))}</span><Button variant="outline" disabled={(page+1)*18>=(mode==='dossiers'?list:storyList).length} onClick={()=>setPage(p=>p+1)}>Next<ChevronRight size={14}/></Button></div></>}
 </>}
 </section>;
}