import {useEffect,useState} from 'react';
import {api} from '../services/applicationClient';
import {Card} from './UI';
const COLORS:Record<string,string>={amber:'#d9a555',cyan:'#00baff',violet:'#b79aff'};
export function CharacterInsignia({color='amber',emblem='compass',size=160}:{color?:string;emblem?:string;size?:number}){
 const stroke=COLORS[color]||COLORS.amber;
 return <svg width={size} height={size} viewBox="0 0 160 160" role="img" aria-label={emblem+' character insignia'}><circle cx="80" cy="80" r="74" fill="#100f10" stroke={stroke} strokeOpacity=".5"/><circle cx="80" cy="80" r="60" fill="none" stroke={stroke} strokeDasharray="2 8"/><path d="M12 80h25m86 0h25M80 12v25m0 86v25" stroke={stroke} strokeOpacity=".6"/><path d={emblem==='archive'?'M48 51h25q7 0 7 8q0-8 7-8h25v57H87q-7 0-7 8q0-8-7-8H48Z':emblem==='signal'?'M48 100q-25-35 0-57m16 50q-16-21 0-39m32 39q16-21 0-39m16 46q25-35 0-57M80 77v42':emblem==='star'?'M80 37l12 28 31 4-23 21 7 32-27-16-27 16 7-32-23-21 31-4Z':'M80 35l16 45-16 45-16-45ZM35 80l45-16 45 16-45 16Z'} fill="none" stroke={stroke} strokeWidth="2"/><circle cx="80" cy="80" r="5" fill={stroke}/></svg>;
}
function LoreChoice({label,type,value,registry,onChange}:{label:string;type:string;value:string;registry:any;onChange:(value:string)=>void}){
 const [search,setSearch]=useState(''),[expanded,setExpanded]=useState(false),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[previewAttempt,setPreviewAttempt]=useState(0);
 const options=Array.from(new Map<string,any>((registry?.entities||[]).filter((e:any)=>e.state==='source-mention'&&e.type===type).sort((a:any,b:any)=>Number(a.scope==='proposal')-Number(b.scope==='proposal')).map((e:any)=>[e.name,e] as [string,any]).reverse()).values()).sort((a:any,b:any)=>a.name.localeCompare(b.name));
 const selected=options.find((e:any)=>e.name===value);
 useEffect(()=>{let live=true;setDetail(null);setError('');if(selected)api('canon/registry/'+encodeURIComponent(selected.id)).then(data=>{if(live)setDetail(data);}).catch(()=>{if(live)setError('Source preview could not load.');});return()=>{live=false;};},[selected?.id,previewAttempt]);
 const filtered=options.filter((e:any)=>e.name.toLowerCase().includes(search.toLowerCase()));
 const visible=expanded||search?filtered:filtered.slice(0,8);
 const evidence=detail?.evidence?.[0];const source=registry?.sources.find((s:any)=>s.id===evidence?.sourceId);
 return <fieldset className="space-y-3"><legend className="text-gold-default uppercase tracking-widest text-sm">{label} <span className="text-neutral-grey text-xs normal-case tracking-normal">· {options.length} documented choices</span></legend><p className="text-neutral-grey text-xs">{type==='species'?'Choose your character’s species from the documented setting.':type==='planets'?'Choose a personal homeworld from the documented worlds.':'Choose an organization your character feels aligned with. This does not grant membership, authority or reputation.'}</p>
 {!registry?<p role="status" className="text-sm text-neutral-grey">Loading documented choices…</p>:options.length===0?<p className="text-sm text-neutral-grey">No documented choices are available in this archive yet. Leave this part of your identity open.</p>:<>
 {options.length>8&&<input aria-label={'Search '+label.toLowerCase()} className="w-full bg-black/50 border border-neutral-grey/30 p-3 text-sm" value={search} onChange={e=>setSearch(e.target.value)} placeholder={'Search '+label.toLowerCase()+'…'}/>}
 <div className="grid sm:grid-cols-2 gap-2"><button type="button" aria-pressed={!value} onClick={()=>onChange('')} className={'text-left border p-3 '+(!value?'border-blue-default bg-blue-default/10':'border-neutral-grey/20')}><span className="text-sm">{type==='factions'?'Independent / no affiliation':'Leave undisclosed'}</span><span className="block text-xs text-neutral-grey mt-1">You can decide later.</span></button>{visible.map((e:any)=><button type="button" key={e.id} aria-pressed={value===e.name} onClick={()=>onChange(e.name)} className={'text-left border p-3 transition-colors '+(value===e.name?'border-gold-default bg-gold-default/10':'border-neutral-grey/20 hover:border-gold-default/60')}><span className="text-sm text-gold-default">{e.name}</span>{e.scope==='proposal'&&<span className="block text-[10px] text-attention-default uppercase mt-1">PR source · not established canon</span>}{e.classification&&<span className="block text-[10px] uppercase text-blue-default mt-1">{e.classification}</span>}{e.summary&&<span className="block text-xs text-neutral-grey mt-2 leading-relaxed line-clamp-3">{e.summary}</span>}<span className="block text-xs text-neutral-grey mt-2">{e.sourceIds?.length||new Set(e.evidence?.map((v:any)=>v.sourceId)||[]).size} source works · inspect evidence {value===e.name?'✓':'→'}</span></button>)}</div>
 {!search&&options.length>8&&<button type="button" className="text-xs text-blue-default underline py-2" onClick={()=>setExpanded(!expanded)}>{expanded?'Show fewer choices':'Show all '+options.length+' choices'}</button>}{search&&!filtered.length&&<p className="text-sm text-neutral-grey">No matching documented choice.</p>}
 </>}
 {selected&&<div className="border-l-2 border-blue-default/50 pl-4 py-2"><p className="text-sm text-blue-default">Source dossier · {selected.name}</p>{selected.scope==='proposal'&&<p className="text-xs text-attention-default mt-2">Documented in a pull-request source. This character option is personal roleplay and does not establish accepted canon.</p>}{error?<div role="status" className="text-xs text-neutral-grey mt-2">{error} <button type="button" className="text-blue-default underline" onClick={()=>setPreviewAttempt(v=>v+1)}>Retry source preview</button></div>:!detail?<p role="status" className="text-xs text-neutral-grey mt-2">Retrieving source evidence…</p>:evidence?<><blockquote className="text-sm text-neutral-grey mt-3 leading-relaxed whitespace-pre-wrap">“{evidence.context}”</blockquote><p className="text-xs text-gold-default mt-3">{source?.title||evidence.sourceId}</p><p className="text-xs text-neutral-grey mt-2">{new Set(detail.evidence.map((e:any)=>e.sourceId)).size} source works. This excerpt supports the setting option; your personal origin is a roleplay choice.</p></>:<p className="text-xs text-neutral-grey mt-2">No narrative excerpt is available for this option.</p>}</div>}
 </fieldset>;
}
export default function CharacterBuilder({initial,registry,busy,onSave,onCancel}:{initial?:any;registry:any;busy:boolean;onSave:(values:any)=>void;onCancel?:()=>void}){
 const [values,setValues]=useState({name:initial?.name||'',pronouns:initial?.pronouns||'',emblem:initial?.emblem||'compass',color:initial?.color||'amber',species:initial?.species||'',homeworld:initial?.homeworld||'',affiliation:initial?.affiliation||'',specialty:initial?.specialty||'explorer',backstory:initial?.backstory||''});
 const update=(key:string,value:string)=>setValues(v=>({...v,[key]:value}));const input='block w-full mt-2 bg-black/50 border border-neutral-grey/30 p-3 text-sm focus:border-blue-default';
 const approaches=[['explorer','Explore the archive freely and follow evidence across stories.'],['cartographer','Prioritize world and location investigations in your expedition board.'],['researcher','Prioritize species and technology investigations in your expedition board.'],['archivist','Prioritize organization investigations and their source history.']];
 return <section className="space-y-6"><header><p className="text-blue-default text-xs uppercase tracking-[.3em]">Character dossier / Alien Worlds</p><h2 className="text-3xl text-gold-default uppercase italic font-bold mt-2">{initial?'Refine your identity':'Who enters the archive?'}</h2><p className="text-sm text-neutral-grey mt-3 max-w-3xl">Choose a species, homeworld and organization affinity from the documented setting. Inspect their source excerpts as you build your character. Your personal identity stays separate from published canon.</p></header>
 <form onSubmit={e=>{e.preventDefault();onSave(values);}} className="grid lg:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)] gap-6 items-start"><div className="space-y-5">
 <Card title="01 · Personal identity"><div className="space-y-5"><label className="block text-sm">Character name<input required minLength={2} maxLength={40} className={input} value={values.name} onChange={e=>update('name',e.target.value)}/></label><label className="block text-sm">Pronouns <span className="text-neutral-grey">(optional)</span><input maxLength={40} className={input} value={values.pronouns} onChange={e=>update('pronouns',e.target.value)}/></label><fieldset><legend className="text-sm mb-3">Insignia</legend><div className="grid grid-cols-4 gap-2">{['compass','star','archive','signal'].map(emblem=><button key={emblem} type="button" aria-pressed={values.emblem===emblem} aria-label={emblem+' insignia'} onClick={()=>update('emblem',emblem)} className={'border p-1 flex flex-col items-center '+(values.emblem===emblem?'border-gold-default bg-gold-default/10':'border-neutral-grey/20')}><CharacterInsignia size={48} emblem={emblem} color={values.color}/><span className="text-[10px] uppercase pb-2">{emblem}</span></button>)}</div></fieldset><fieldset><legend className="text-sm mb-3">Signal color</legend><div className="flex flex-wrap gap-3">{Object.entries(COLORS).map(([color,hex])=><button key={color} type="button" onClick={()=>update('color',color)} aria-pressed={values.color===color} className="border px-4 py-2 text-xs uppercase" style={{color:hex,borderColor:values.color===color?hex:'#333'}}>{color}</button>)}</div></fieldset></div></Card>
 <Card title="02 · Species and origins"><div className="space-y-8"><LoreChoice label="Species" type="species" value={values.species} registry={registry} onChange={v=>update('species',v)}/><div className="border-t border-neutral-grey/20"/><LoreChoice label="Homeworld" type="planets" value={values.homeworld} registry={registry} onChange={v=>update('homeworld',v)}/><div className="border-t border-neutral-grey/20"/><LoreChoice label="Organization affinity" type="factions" value={values.affiliation} registry={registry} onChange={v=>update('affiliation',v)}/></div></Card>
 <Card title="03 · Your purpose"><div className="space-y-5"><fieldset><legend className="text-sm mb-3">How will you explore?</legend><div className="grid sm:grid-cols-2 gap-3">{approaches.map(([role,description])=><button type="button" key={role} aria-pressed={values.specialty===role} onClick={()=>update('specialty',role)} className={'text-left border p-4 '+(values.specialty===role?'border-gold-default bg-gold-default/10':'border-neutral-grey/20')}><span className="text-gold-default uppercase text-sm">{role}</span><p className="text-xs text-neutral-grey mt-2 leading-relaxed">{description}</p></button>)}</div></fieldset><label className="block text-sm">Personal backstory<textarea rows={5} maxLength={1200} value={values.backstory} onChange={e=>update('backstory',e.target.value)} className={input} placeholder="What brought your character to the archive? What do they hope to discover?"/></label><p className="text-xs text-neutral-grey text-right">{values.backstory.length}/1200 · personal fiction</p></div></Card>
 <div className="flex flex-wrap justify-between gap-3 pb-5">{onCancel&&<button type="button" onClick={onCancel} className="text-sm text-neutral-grey p-3">Cancel changes</button>}<button disabled={busy||values.name.trim().length<2} className="px-5 py-3 bg-gold-default text-black text-xs uppercase tracking-widest disabled:opacity-40">{busy?'Saving dossier…':initial?'Save character':'Create character & choose expedition'}</button></div></div>
 <aside className="space-y-5 lg:sticky lg:top-5"><Card className="border-gold-default/30 text-center py-6"><p className="text-[10px] text-neutral-grey uppercase tracking-[.35em]">Live character dossier</p><div className="flex justify-center my-5"><CharacterInsignia color={values.color} emblem={values.emblem} size={112}/></div><h3 className="text-2xl uppercase font-bold text-gold-default break-words">{values.name||'Your explorer'}</h3><p className="text-xs text-neutral-grey mt-2">{values.pronouns||'Pronouns undisclosed'}</p><p className="text-blue-default text-xs uppercase tracking-[.25em] mt-4">{values.specialty}</p><dl className="grid grid-cols-2 border-y border-neutral-grey/20 my-5 py-4 gap-4 text-xs"><div><dt className="text-neutral-grey mb-2">SPECIES</dt><dd>{values.species||'Undisclosed'}</dd></div><div><dt className="text-neutral-grey mb-2">HOMEWORLD</dt><dd>{values.homeworld||'Undisclosed'}</dd></div><div className="col-span-2"><dt className="text-neutral-grey mb-2">ORGANIZATION AFFINITY</dt><dd>{values.affiliation||'Independent'}</dd></div></dl>{values.backstory&&<p className="text-sm text-neutral-grey leading-relaxed text-left whitespace-pre-wrap break-words">{values.backstory}</p>}</Card><Card title="Your first expedition"><ol className="space-y-3 text-sm text-neutral-grey"><li><span className="text-gold-default">01</span> Choose a source-backed investigation from your expedition board.</li><li><span className="text-gold-default">02</span> Read its linked works and record your discoveries.</li><li><span className="text-gold-default">03</span> Compare the source evidence to complete the checkpoint and earn XP.</li></ol><p className="mt-4 text-xs text-blue-default leading-relaxed">Your choices prioritize relevant investigations. All stories remain open, and you can edit your identity without losing progress.</p></Card></aside></form></section>;
}
