import {portalFetch as fetch} from '../services/pagesRuntime';
import {useEffect,useRef,useState} from 'react';
import {Button,Badge} from './UI';
import {LoreContent} from './LoreContent';
import {api} from '../services/applicationClient';
export default function CorpusLibrary({user}:{user:any}){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<any>(null),[section,setSection]=useState<any>(null),[sectionPage,setSectionPage]=useState(0),[error,setError]=useState(''),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[job,setJob]=useState<any>(null),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);const serial=useRef(0);
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{api('corpus/'+(query.trim()?'search?q='+encodeURIComponent(query.trim())+'&':'sources?')+'offset='+page*12+'&limit=12').then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)});},200);return()=>{live=false;clearTimeout(timer)}},[query,page,revision]);
 useEffect(()=>{if(!selected)return;const request=++serial.current;setSection(null);setError('');api('corpus/sources/'+selected.id+'/sections?offset='+sectionPage+'&limit=1').then(d=>{if(request===serial.current)setSection(d)}).catch(e=>{if(request===serial.current)setError(e.message)});return()=>{serial.current++}},[selected?.id,sectionPage]);
 useEffect(()=>{if(!job||['complete','failed'].includes(job.state))return;let live=true;const timer=setInterval(()=>{api('corpus/jobs/'+job.id).then(j=>{if(live){setJob(j);if(j.state==='complete')setRevision(v=>v+1)}}).catch(e=>{if(live)setError(e.message)});},1500);return()=>{live=false;clearInterval(timer)}},[job?.id,job?.state]);
 async function open(source:any,sectionId?:string,sectionIndex?:number){setSelected(source);setSectionPage(sectionIndex||0);if(sectionId&&sectionIndex===undefined){try{let offset=0;while(offset<source.sections){const d=await api('corpus/sources/'+source.id+'/sections?offset='+offset+'&limit=100');const index=d.sections.findIndex((s:any)=>s.id===sectionId);if(index>=0){setSectionPage(offset+index);break}offset+=100}}catch(e:any){setError(e.message)}}}
 async function upload(){if(!file||!title.trim())return;setBusy(true);setError('');try{const response=await fetch('/api/corpus/imports',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'text/plain; charset=utf-8','X-Loreworks':'1','X-Lore-Title':encodeURIComponent(title.trim())},body:file});const result=await response.json();if(!response.ok)throw Error(result.error);setJob(result);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="max-w-6xl mx-auto space-y-6"><header><p className="text-xs text-blue-default uppercase tracking-widest">Full-text source library</p><h2 className="text-3xl text-gold-default uppercase font-bold mt-2">Search every passage</h2><p className="text-sm text-neutral-grey mt-3">Search the complete text, including names the entity catalog has not classified yet. Originals are preserved; chapters and long sections are read in manageable parts.</p></header>{error&&<p role="alert" className="border border-error-default p-3 text-sm">{error}</p>}
 {selected?<><Button variant="ghost" onClick={()=>{setSelected(null);setSection(null)}}>← Back to source library</Button><div className="border border-blue-default/30 p-5"><Badge color={selected.scope==='canon'?'blue':'attention'}>{selected.scope==='canon'?'Main archive':'Supplementary source'}</Badge><h3 className="text-xl text-gold-default mt-3">{selected.title}</h3><p className="text-xs text-neutral-grey mt-3">{selected.sections} reading sections · original preserved</p><div className="flex flex-wrap items-center gap-3 mt-4"><Button variant="outline" disabled={!sectionPage} onClick={()=>setSectionPage(p=>p-1)}>Previous section</Button><label className="text-xs text-neutral-grey">Section <input aria-label="Reading section" type="number" min={1} max={selected.sections} value={sectionPage+1} onChange={e=>setSectionPage(Math.max(0,Math.min(selected.sections-1,Number(e.target.value)-1)))} className="bg-black border border-neutral-grey/30 p-2 w-20"/> / {selected.sections}</label><Button variant="outline" disabled={sectionPage+1>=selected.sections} onClick={()=>setSectionPage(p=>p+1)}>Next section</Button></div></div>{!section?<p role="status">Loading preserved section…</p>:section.sections.map((s:any)=><article key={s.id}><p className="text-xs text-blue-default mb-4">{[...s.ancestry,s.heading].filter(Boolean).join(' / ')||'Opening text'}</p><LoreContent content={s.text} onLinkClick={target=>{setSelected(null);setQuery(target);setPage(0)}}/><details className="text-xs text-neutral-grey mt-6"><summary>Source verification</summary><p className="break-all mt-3">Source SHA-256: {selected.hash}</p><p>Original text positions {s.start}–{s.end}. No text omitted between adjacent parts.</p></details></article>)}</>:<>
 <label className="block"><span className="sr-only">Search complete corpus</span><input value={query} onChange={e=>{setData(null);setQuery(e.target.value);setPage(0)}} placeholder="Search any name, phrase or subject — including Elsewhere…" className="w-full bg-black border border-blue-default/40 p-4 text-sm"/></label>{!data?<p role="status">Loading indexed works…</p>:<><p role="status" className="text-xs text-neutral-grey">{data.total} {query?'matching sections':'source works'}</p><div className="grid sm:grid-cols-2 gap-4">{(data.results||data.sources?.map((source:any)=>({source}))).map(({source,section:s,sectionIndex}:any,i:number)=><button key={source.id+':'+(s?.id||i)} onClick={()=>open(source,s?.id,sectionIndex)} className="text-left border border-neutral-grey/25 hover:border-gold-default p-5 bg-neutral-black/60"><Badge color={source.scope==='canon'?'blue':'attention'}>{source.scope==='canon'?'Main archive':'Supplementary source'}</Badge><h3 className="text-gold-default mt-3 text-base">{source.title}</h3><p className="text-sm text-neutral-white/80 mt-2">{s?[...s.ancestry,s.heading].filter(Boolean).join(' / '):source.sections+' reading sections'}</p><p className="text-xs text-blue-default mt-4">Read preserved {s?'passage':'work'} →</p></button>)}</div><div className="flex justify-center gap-4"><Button variant="outline" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="text-xs py-2">{page+1} / {Math.max(1,Math.ceil(data.total/12))}</span><Button variant="outline" disabled={(page+1)*12>=data.total} onClick={()=>setPage(p=>p+1)}>Next</Button></div></>}
 {user?.role==='scribe'&&<details className="border border-gold-default/40 p-5"><summary className="text-gold-default cursor-pointer">Import a lore manuscript</summary><p className="text-sm text-neutral-grey mt-3">Upload UTF-8 Markdown or plain text. The original is preserved and indexed as supplementary material; importing does not grant canon status. Maximum {Math.round((data?.maxImportBytes||20971520)/1048576)} MiB per file.</p><label className="block text-sm mt-4">Work title<input maxLength={240} value={title} onChange={e=>setTitle(e.target.value)} className="block w-full bg-black border border-neutral-grey/30 p-3 mt-2"/></label><input aria-label="Lore manuscript" type="file" accept=".md,.markdown,.txt,text/plain,text/markdown" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(!title&&f)setTitle(f.name)}} className="block max-w-full my-4 text-xs"/><Button disabled={!file||!title.trim()||busy} onClick={upload}>{busy?'Uploading…':'Preserve & index manuscript'}</Button>{job&&<p role="status" className="text-sm text-blue-default mt-3">Import: {job.state}{job.error?' — '+job.error:''}</p>}</details>}
 </>}
 </section>;
}