import PlayerInvestigation from './PlayerInvestigation';
import {useEffect,useState} from 'react';
import {api} from '../services/applicationClient';
import {Card,Badge,Button} from './UI';
import CharacterBuilder,{CharacterInsignia} from './CharacterBuilder';
import {sourceStoryForId,sourceRecordId,sourceTitleForId} from '../constants/sourceArchive';
export default function PlayerProfile({user,onLogin,onExplore,onRead}:{user:any;onLogin:()=>void;onExplore:()=>void;onRead:(id:string)=>void}){
 const [player,setPlayer]=useState<any>(),[registry,setRegistry]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[tab,setTab]=useState('expeditions'),[search,setSearch]=useState(''),[feedback,setFeedback]=useState<Record<string,string>>({});
 useEffect(()=>{let live=true;const load=()=>{if(user)api('player').then(r=>{if(live)setPlayer(r.player)}).catch(e=>{if(live)setError(e.message)});};setPlayer(undefined);load();api('canon/registry').then(r=>{if(live)setRegistry(r)}).catch(e=>{if(live)setError(e.message)});window.addEventListener('player-updated',load);return()=>{live=false;window.removeEventListener('player-updated',load)}},[user?.uid]);
 async function write(path:string,body:any){setBusy(true);setError('');try{const result=await api('player/'+path,body);setPlayer(result.player);window.dispatchEvent(new Event('player-updated'));return result;}catch(e:any){setError(e.message);return null;}finally{setBusy(false);}}
 async function save(values:any){const result=await write(player?'character/update':'character',values);if(result){setEditing(false);window.dispatchEvent(new Event('player-updated'));}}
 const title=(id:string)=>sourceTitleForId(id)||registry?.sources.find((s:any)=>s.id===id)?.title||registry?.entities.find((e:any)=>e.id===id)?.name||player?.expeditions?.find((m:any)=>m.id===id)?.name||player?.missions?.find((m:any)=>m.id===id)?.name||id;
 if(!user)return <Card title="Your expedition starts here"><p className="text-neutral-grey text-sm mb-6">Create a character, choose an investigation, follow its source trail and verify the evidence. Your discoveries form a persistent personal codex.</p><Button onClick={onLogin}>Create your character</Button></Card>;
 if(player===undefined)return <Card title="Loading your dossier">{error?<p role="alert">{error}</p>:<p className="text-neutral-grey text-sm">Retrieving character and expedition records…</p>}</Card>;
 if(!player||editing)return <div className="space-y-5">{error&&<p role="alert" className="text-error-default">{error}</p>}<CharacterBuilder initial={player} registry={registry} busy={busy} onSave={save} onCancel={player?()=>setEditing(false):undefined}/></div>;
 const active=player.expeditions.filter((m:any)=>m.state==='active');const complete=player.expeditions.filter((m:any)=>m.state==='completed');
 const specialtyTypes:any={cartographer:['planets'],researcher:['species','technology'],archivist:['factions'],explorer:[]};const preferred=specialtyTypes[player.specialty||'explorer']||[];const affinity=[player.species,player.homeworld,player.affiliation].filter(Boolean);const relevance=(m:any)=>Number(affinity.includes(m.entityName))*2+Number(preferred.includes(m.discipline));
 const available=player.expeditions.filter((m:any)=>m.state==='available'&&m.entityName.toLowerCase().includes(search.toLowerCase())).sort((a:any,b:any)=>relevance(b)-relevance(a));
 return <section className="max-w-6xl mx-auto space-y-6"><div className="flex flex-wrap justify-between items-end gap-4"><div><p className="text-xs tracking-[.3em] uppercase text-blue-default">Personal archive / expedition command</p><h2 className="text-3xl font-bold uppercase italic text-gold-default mt-2">Explorer Profile</h2></div><Button variant="outline" onClick={()=>setEditing(true)}>Edit character</Button></div>{error&&<p role="alert" className="border border-error-default/40 p-4 text-error-default">{error}</p>}
 <Card><div className="flex flex-wrap items-center gap-6"><CharacterInsignia color={player.color} emblem={player.emblem} size={112}/><div className="flex-1 min-w-40"><h3 className="text-2xl uppercase font-bold text-gold-default">{player.name}</h3><p className="text-xs text-neutral-grey mt-2">{[player.pronouns,player.species,player.homeworld,player.affiliation].filter(Boolean).join(' · ')||'Origins undisclosed'}</p><p className="text-blue-default text-xs uppercase tracking-widest mt-3">{player.specialty||'explorer'}</p></div><div><Badge>Level {player.level}</Badge><p className="text-xl text-gold-default mt-3">{player.xp} XP</p><p className="text-xs text-neutral-grey mt-1">{player.nextLevelXp-player.xp} to the next level</p></div></div><progress aria-label="Level progress" value={player.xp-100*(player.level-1)**2} max={player.nextLevelXp-100*(player.level-1)**2} className="w-full h-2 mt-6"/>{player.backstory&&<details className="mt-5 text-sm"><summary className="text-blue-default cursor-pointer">Character backstory</summary><p className="mt-3 whitespace-pre-wrap text-neutral-grey leading-relaxed">{player.backstory}</p></details>}</Card>
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['Stories',player.counts.stories],['Entities',player.counts.entities],['Worlds',player.counts.planets],['Expeditions',complete.length]].map(([label,value])=><Card key={label}><p className="text-xl text-gold-default">{value}</p><p className="text-[10px] uppercase text-neutral-grey mt-1">{label}</p></Card>)}</div>
 <nav aria-label="Player sections" className="flex border-b border-neutral-grey/25 overflow-x-auto">{[['expeditions','Expeditions'],['codex','Personal codex'],['milestones','Milestones'],['journal','Journey log']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined} className={'px-4 py-3 shrink-0 text-xs uppercase tracking-wider '+(tab===id?'text-gold-default border-b-2 border-gold-default':'text-neutral-grey')}>{label}</button>)}</nav>
 {tab==='expeditions'&&<><div><h3 className="text-gold-default uppercase tracking-widest">Active investigations · {active.length}/2</h3><p className="text-neutral-grey text-sm mt-2">Choose a route, recover field notes from real source passages, and decide what their connection supports.</p></div>{active.length?active.map((m:any)=>m.version===2?<PlayerInvestigation key={m.id} mission={m} busy={busy} onRead={onRead} onAction={(action,value)=>write('expeditions/action',{id:m.id,action,value})} onComplete={sourceId=>write('expeditions/complete',{id:m.id,sourceId})} onAbandon={()=>write('expeditions/abandon',{id:m.id})}/>:<Card key={m.id} title={m.name}><div className="flex flex-wrap gap-2"><Badge>{m.discipline}</Badge><Badge color="blue">{m.xp} XP on completion</Badge></div><p className="text-sm text-neutral-grey mt-4">{m.brief}</p><ol className="mt-5 space-y-3">{m.objectives.map((o:any,i:number)=><li key={o.id} className="border border-neutral-grey/20 p-3 flex gap-3 items-center"><span className={o.complete?'text-success-default':'text-gold-default'}>{o.complete?'✓':i+1}</span><button onClick={()=>onRead(o.id)} className="text-left text-sm text-blue-default hover:underline flex-1">{o.title}</button><span className="text-[10px] text-neutral-grey uppercase">{o.complete?'Recorded':'Read source →'}</span></li>)}</ol><details className="mt-5" open={m.ready}><summary className="cursor-pointer text-gold-default text-sm">Evidence checkpoint {m.ready?'· ready':'· unlock by recording both sources'}</summary><blockquote className="border-l border-blue-default/40 pl-4 my-4 text-sm text-neutral-grey leading-relaxed">“{m.quote}”</blockquote><p className="text-sm mb-3">Which linked source contains this passage?</p><div className="space-y-2">{m.options.map((o:any)=><button key={o.id} disabled={!m.ready||busy} onClick={async()=>{const result=await write('expeditions/complete',{id:m.id,sourceId:o.id});if(result)setFeedback(f=>({...f,[m.id]:result.feedback}));}} className="block w-full text-left border border-neutral-grey/30 p-3 text-sm hover:border-blue-default disabled:opacity-40">{o.title}</button>)}</div>{feedback[m.id]&&<p role="status" className="text-gold-default text-sm mt-3">{feedback[m.id]}</p>}</details><button disabled={busy} onClick={()=>write('expeditions/abandon',{id:m.id})} className="text-xs text-neutral-grey mt-5 underline">Abandon investigation</button></Card>):<Card><p className="text-sm text-neutral-grey">Choose an evidence trail below to begin. Your species, homeworld, organization affinity and specialty put relevant trails first.</p></Card>}
 {complete.length>0&&<Card title="Completed investigations"><div className="flex flex-wrap gap-2">{complete.map((m:any)=><Badge key={m.id} color="success">✓ {m.name}</Badge>)}</div></Card>}
 <div className="flex flex-wrap justify-between gap-3 items-center"><h3 className="text-gold-default uppercase tracking-widest">Choose your next trail</h3><input aria-label="Search expeditions" placeholder="Find a world, species or technology…" value={search} onChange={e=>setSearch(e.target.value)} className="bg-black border border-neutral-grey/30 p-3 text-sm max-w-full w-80"/></div><div className="grid sm:grid-cols-2 gap-4">{available.slice(0,search?50:8).map((m:any)=><Card key={m.id} title={m.name}><Badge color="blue">{m.discipline}</Badge>{affinity.includes(m.entityName)&&<span className="ml-2 text-[10px] text-gold-default uppercase">From your character dossier</span>}<p className="text-sm text-neutral-grey my-4 leading-relaxed">{m.brief}</p><p className="text-xs text-neutral-grey mb-4">Choose a route · recover 2 notes · connect evidence · {m.xp} XP</p><Button disabled={busy||active.length>=2} onClick={()=>write('expeditions/start',{id:m.id})}>Start investigation</Button></Card>)}</div>{!available.length&&<p className="text-neutral-grey">No matching trails. Try another documented entity.</p>}</>}
 {tab==='codex'&&<Card title="Personal codex"><div className="grid sm:grid-cols-2 gap-6"><div><h3 className="text-blue-default mb-3">Studied works</h3>{Object.keys(player.discoveries.story).length?Object.keys(player.discoveries.story).map(id=><button key={id} onClick={()=>onRead(sourceRecordId(id))} className="block text-left text-sm py-3 text-neutral-grey hover:text-gold-default">{title(id)} →</button>):<p className="text-sm text-neutral-grey">Your source discoveries will appear here.</p>}</div><div><h3 className="text-blue-default mb-3">Collected entities</h3>{Object.keys(player.discoveries.entity).map(id=><p key={id} className="text-sm py-2">{title(id)}</p>)}<Button onClick={onExplore}>Explore entity registry</Button><h3 className="text-blue-default mt-6 mb-3">Worlds visited</h3><p className="text-sm text-neutral-grey">{Object.keys(player.discoveries.planet).join(' · ')||'No worlds recorded yet.'}</p></div></div></Card>}
 {tab==='milestones'&&<><div className="flex flex-wrap gap-2">{player.achievements.map((a:string)=><Badge key={a} color="success">{a}</Badge>)}</div><div className="grid sm:grid-cols-2 gap-4">{player.missions.map((m:any)=><Card key={m.id} title={m.name}><Badge>{m.completed?'Completed':'Exploration milestone'}</Badge><p className="text-sm text-neutral-grey my-4">{m.description}</p><progress aria-label={m.name+' progress'} max={m.total} value={m.progress} className="w-full h-2"/><p className="text-xs mt-3">{m.progress}/{m.total} · {m.xp} XP</p></Card>)}</div></>}
 {tab==='journal'&&<Card title="Journey log">{player.activity.length?player.activity.slice(0,30).map((a:any,i:number)=><p key={i} className="text-sm py-3 border-b border-neutral-grey/15"><span className="text-gold-default">+{a.xp} XP</span> · {title(a.target)}<span className="block text-xs text-neutral-grey mt-1">{new Date(a.at).toLocaleString()}</span></p>):<p className="text-neutral-grey text-sm">Your completed discoveries will be recorded here.</p>}</Card>}
 </section>;
}