import {useState} from 'react';
import {Card,Badge,Button} from './UI';
export default function PlayerInvestigation({mission:m,busy,onRead,onAction,onComplete,onAbandon}:{mission:any;busy:boolean;onRead:(id:string)=>void;onAction:(action:string,value:string)=>Promise<any>;onComplete:(value:string)=>Promise<any>;onAbandon:()=>void}){
 const [feedback,setFeedback]=useState(''),[cooling,setCooling]=useState(false);
 const act=async(action:string,value:string)=>{const result=action==='conclude'?await onComplete(value):await onAction(action,value);if(result?.feedback)setFeedback(result.feedback);if(action!=='route'){setCooling(true);setTimeout(()=>setCooling(false),3100);}};
 const next=m.objectives.find((o:any)=>!o.complete),clue=m.clues.find((c:any)=>c.sourceId===next?.id);
 const steps=[{label:'Choose route',done:!!m.route},{label:'First field note',done:m.objectives[0]?.complete},{label:'Second field note',done:m.objectives[1]?.complete},{label:'Draw conclusion',done:m.state==='completed'}];
 return <Card title={m.name}><div className="flex flex-wrap gap-2"><Badge>{m.discipline}</Badge><Badge color="blue">{m.xp} XP · once per investigation</Badge></div><p className="text-sm text-neutral-grey my-4">{m.brief}</p><ol className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-5">{steps.map((s,i)=><li key={s.label} className={'border p-3 text-xs '+(s.done?'border-success-default/40 text-success-default':'border-neutral-grey/20 text-neutral-grey')}><span className="block mb-1">{s.done?'✓':String(i+1).padStart(2,'0')}</span>{s.label}</li>)}</ol>
 {m.stage==='route'&&<div><h4 className="text-gold-default text-sm mb-3">Where will you begin?</h4><p className="text-xs text-neutral-grey mb-4">Both routes follow the same documented entity. Your choice determines which source you investigate first.</p><div className="grid sm:grid-cols-2 gap-3">{m.objectives.map((o:any)=><button key={o.id} disabled={busy} onClick={()=>act('route',o.id)} className="p-4 text-left border border-blue-default/30 hover:border-blue-default text-sm text-blue-default disabled:opacity-40">Begin with {o.title} →</button>)}</div></div>}
 {m.stage==='fieldwork'&&next&&clue&&<div><h4 className="text-gold-default text-sm">Recover a field note · {next.title}</h4><p className="text-xs text-neutral-grey mt-3 mb-4">Open this source and compare its wording. Which of these actual archive passages belongs to it? Recovering a note records expedition evidence; your ordinary reading discoveries remain separate.</p><Button variant="outline" onClick={()=>onRead(next.id)}>Read {next.title}</Button><div className="space-y-3 mt-4">{clue.options.map((o:any,i:number)=><button key={o.key} disabled={busy||cooling} onClick={()=>act('clue',o.key)} className="block w-full text-left border border-neutral-grey/25 hover:border-blue-default p-4 disabled:opacity-40"><span className="text-xs text-blue-default uppercase">Field note {i+1}</span><span className="block text-sm text-neutral-grey leading-relaxed mt-2">“{o.quote}”</span></button>)}</div></div>}
 {m.stage==='conclusion'&&<div><h4 className="text-gold-default text-sm">Two appearances. What do they establish?</h4><p className="text-xs text-neutral-grey mt-3 mb-4">Your notes place {m.entityName} in both linked works. Choose a conclusion supported by those appearances alone.</p><div className="space-y-2">{[['shared-appearance','The same documented entity appears in both source works.'],['chronology','These appearances alone establish which story happened first.'],['causation','These appearances alone establish a causal link between the stories.']].map(([id,label])=><button key={id} disabled={busy||cooling} onClick={()=>act('conclude',id)} className="block w-full border border-neutral-grey/25 p-4 hover:border-gold-default text-left text-sm disabled:opacity-40">{label}</button>)}</div></div>}
 {feedback&&<p role="status" className="mt-4 text-blue-default text-sm leading-relaxed border-l border-blue-default/40 pl-3">{feedback}</p>}
 {m.objectives.some((o:any)=>o.complete)&&<details className="mt-5"><summary className="text-xs text-gold-default cursor-pointer">Recovered evidence board</summary>{m.objectives.filter((o:any)=>o.complete).map((o:any)=><button key={o.id} className="block py-3 text-xs text-neutral-grey hover:text-blue-default" onClick={()=>onRead(o.id)}>✓ Verified field note · {o.title} →</button>)}</details>}
 <button disabled={busy} onClick={onAbandon} className="mt-5 text-xs text-neutral-grey underline">Abandon investigation</button>
 </Card>;
}
