import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const repo=process.env.LORE_REPO_DIR;if(!repo)throw Error('Set LORE_REPO_DIR to the verified upstream Git clone.');
const git=(...args)=>execFileSync('git',['-C',repo,...args],{encoding:'utf8',maxBuffer:32*1024*1024});
const commit=git('rev-parse','HEAD').trim(),body=git('show',commit+':README.md').replace(/\r\n/g,'\n');
const clean=s=>s.replace(/<[^>]+>/g,'').replace(/\*|`/g,'').trim();const hash=s=>createHash('sha256').update(s).digest('hex');
const headings=[...body.matchAll(/^(#{1,6})[ \t]+(.+?)\s*$|^<h1\b[^>]*>(.+?)<\/h1>\s*$/gm)].map(m=>({level:m[1]?.length||1,title:clean(m[2]||m[3]),start:m.index,end:m.index+m[0].length,line:body.slice(0,m.index).split('\n').length}));
const firstStoryH1=headings.find(h=>h.level===1&&h.start>0)?.start??body.length;
const roots=headings.filter(h=>h.level===1||(h.level===2&&h.start<firstStoryH1));
const canonicalText=fs.readFileSync('src/constants/canonicalLore.ts','utf8');const legacy=JSON.parse(canonicalText.slice(canonicalText.indexOf('= [')+2,canonicalText.lastIndexOf('];')+1));
const used=new Map();const stories=roots.map((h,i)=>{const end=roots[i+1]?.start??body.length;const slug=h.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const n=used.get(slug)||0;used.set(slug,n+1);const content=body.slice(h.start,end).trim();return {id:'source_'+slug+(n?'-'+(n+1):''),title:h.title,content,authorId:'federation-archive',authorName:'Author not attributed in this source',type:'canon',status:'active',category:'General',tags:[],createdAt:{seconds:0},voteCount:0,sourceUrl:'https://github.com/Alien-Worlds/the-lore/blob/'+commit+'/README.md#L'+h.line,sourceCommit:commit,sourceHash:hash(content),sourceStart:h.start,sourceEnd:end,sourceLine:h.line,contentComplete:true,chapters:headings.filter(c=>c.start>h.start&&c.start<end).map(c=>({title:c.title,level:c.level,offset:c.start-h.start,line:c.line})),legacyIds:[]};});
const compact=s=>s.replace(/\s+/g,' ').trim();const unmatched=[];for(const old of legacy){const cleanLegacy=old.content.replace(/\n+<h1\b[^>]*>[^<]+<\/h1>\s*$/, '');const matches=stories.filter(s=>compact(s.content).includes(compact(cleanLegacy)));if(matches.length===1)matches[0].legacyIds.push(old.id);else unmatched.push({id:old.id,title:old.title,matches:matches.map(s=>s.id)});}
const pinned=JSON.parse(fs.readFileSync('server/data/verified_pr_sources.json','utf8'));const redirects={};for(const old of legacy){const parent=stories.find(s=>s.legacyIds.includes(old.id));if(parent)redirects[old.id]={id:parent.id,title:parent.title};else{const matches=Object.values(pinned).filter(p=>compact(p.content).includes(compact(old.content)));if(matches.length===1)redirects[old.id]={id:'lore_worlds_'+matches[0].pr_id,title:matches[0].title};}}fs.writeFileSync('server/data/legacy_source_redirects.json',JSON.stringify(redirects,null,2)+'\n');
const output={source:{repository:'Alien-Worlds/the-lore',commit,path:'README.md',sha256:hash(body)},stories,unmatchedLegacy:unmatched};
fs.writeFileSync('server/data/source_archive.json',JSON.stringify(output,null,2)+'\n');fs.writeFileSync('G:/Loreworks/research/upstream-source.json',JSON.stringify(output.source,null,2));console.log(JSON.stringify({commit,stories:stories.length,chapters:stories.reduce((n,s)=>n+s.chapters.length,0),mappedLegacy:legacy.length-unmatched.length,unmatched}));