import fs from 'node:fs';import {execFileSync} from 'node:child_process';import {extractAddedMarkdownFromPatch,extractNarrativeTitle,hashNarrative} from '../server/githubPrNarrative.js';
const repo=process.env.LORE_REPO_DIR;if(!repo)throw Error('LORE_REPO_DIR required');const git=(...args)=>execFileSync('git',['-c','core.quotepath=false','-C',repo,...args],{encoding:'utf8',maxBuffer:32*1024*1024});
const proposals=JSON.parse(fs.readFileSync('G:/Loreworks/research/proposal-audit.json','utf8'));const commits=git('log','--first-parent','--format=%H%x09%s','origin/main').trim().split('\n');const output={},report=[];
for(const proposal of proposals){const id=Number(proposal.pull_request_id);if(!Number.isInteger(id)||id<=0)continue;try{
const merged=commits.filter(l=>new RegExp('\\(#'+id+'\\)$').test(l));if(merged.length>1)throw Error('Ambiguous merge commits');
const head=merged.length?merged[0].split('\t')[0]:git('rev-parse','origin/pr/'+id).trim();const base=merged.length?git('rev-parse',head+'^').trim():git('merge-base','origin/main',head).trim();
const names=git('diff','--name-only',base,head,'--','*.md','*.markdown').trim().split('\n').filter(Boolean);if(names.length!==1)throw Error('Expected one narrative file; found '+names.length);
const file=names[0];const status=git('diff','--find-renames=10%','--name-status',base,head,'--','*.md','*.markdown');const patch=git('diff','--find-renames=10%','--unified=0',base,head,'--','*.md','*.markdown');const content=(file.toLowerCase().endsWith('readme.md')||/^R[0-9]/m.test(status)?extractAddedMarkdownFromPatch(patch):git('show',head+':'+file)).replace(/\r\n/g,'\n').trim();if(content.length<120)throw Error('No complete narrative addition');
const first=content.split('\n').find(l=>l.trim());const heading=/^#{1,3}\s+/.test(first||'')?extractNarrativeTitle(content,proposal.title):proposal.title;
const record={pr_id:id,pr_url:'https://github.com/Alien-Worlds/the-lore/pull/'+id,title:heading,author:'',head_sha:head,base_sha:base,file_path:file,source_kind:merged.length?'verified_git_merge_diff':'verified_git_pull_ref_diff',content,content_sha256:hashNarrative(content),status:'resolved',reason:'pinned_exact_git_change',reviewed_at:new Date().toISOString()};output[id]=record;report.push({id,title:heading,length:content.length,source:record.source_kind});
}catch(error){report.push({id,error:error.message});}}
fs.writeFileSync('server/data/verified_pr_sources.json',JSON.stringify(output,null,2)+'\n');fs.writeFileSync('G:/Loreworks/research/exact-source-recovery.json',JSON.stringify(report,null,2));console.log(JSON.stringify({resolved:Object.keys(output).length,missing:report.filter(r=>r.error),examples:report.filter(r=>[61,85,94,101,104].includes(r.id))}));